Fix dependences versions. Remove annotation tool
DHI/tsod pull request #49
Opened 2023-12-13 13:04 UTC by charalamm

2023-12-14 14:13 UTC, ecomodeller requested changes

2023-12-14 14:13 UTC, ecomodeller commented on setup.py
> +        "pandas==2.1.*",
Don't pin versions here.

`tsod` is a library intended to use together with other libraries. Pinning versions will make this very difficult.

2023-12-18 09:24 UTC, charalamm commented
@ecomodeller How about now? I guess restricting old major versions is needed, since there is a high chance they include breaking changes?
I have also changed pandas assignments lines in `tsod/detectors.py` to fix some warining the tests was giving.

2023-12-18 13:17 UTC, ecomodeller commented
> @ecomodeller How about now? I guess restricting old major versions is needed, since there is a high chance they include breaking changes? I have also changed pandas assignments lines in `tsod/detectors.py` to fix some warining the tests was giving.

Well, pandas v2 was released earlier this year. I would be surprised if it actually needs v2.

2023-12-19 12:25 UTC, charalamm commented
@ecomodeller how about now?

2023-12-19 13:00 UTC, ecomodeller approved these changes

2023-12-19 13:00 UTC, merged